// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Article_StatusType int32

const (
	Article_DRAFT       Article_StatusType = 0
	Article_PUBLISHED   Article_StatusType = 1
	Article_UNPUBLISHED Article_StatusType = 2
)

var Article_StatusType_name = map[int32]string{
	0: "DRAFT",
	1: "PUBLISHED",
	2: "UNPUBLISHED",
}

var Article_StatusType_value = map[string]int32{
	"DRAFT":       0,
	"PUBLISHED":   1,
	"UNPUBLISHED": 2,
}

func (x Article_StatusType) String() string {
	return proto.EnumName(Article_StatusType_name, int32(x))
}

func (Article_StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0, 0}
}

type Article struct {
	Id                   int32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string             `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string             `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status               Article_StatusType `protobuf:"varint,4,opt,name=status,proto3,enum=main.Article_StatusType" json:"status,omitempty"`
	Tags                 []*Article_Tags    `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetStatus() Article_StatusType {
	if m != nil {
		return m.Status
	}
	return Article_DRAFT
}

func (m *Article) GetTags() []*Article_Tags {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Article_Tags struct {
	TagId                int32    `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article_Tags) Reset()         { *m = Article_Tags{} }
func (m *Article_Tags) String() string { return proto.CompactTextString(m) }
func (*Article_Tags) ProtoMessage()    {}
func (*Article_Tags) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0, 0}
}

func (m *Article_Tags) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article_Tags.Unmarshal(m, b)
}
func (m *Article_Tags) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article_Tags.Marshal(b, m, deterministic)
}
func (m *Article_Tags) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article_Tags.Merge(m, src)
}
func (m *Article_Tags) XXX_Size() int {
	return xxx_messageInfo_Article_Tags.Size(m)
}
func (m *Article_Tags) XXX_DiscardUnknown() {
	xxx_messageInfo_Article_Tags.DiscardUnknown(m)
}

var xxx_messageInfo_Article_Tags proto.InternalMessageInfo

func (m *Article_Tags) GetTagId() int32 {
	if m != nil {
		return m.TagId
	}
	return 0
}

func (m *Article_Tags) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.Article_StatusType", Article_StatusType_name, Article_StatusType_value)
	proto.RegisterType((*Article)(nil), "main.Article")
	proto.RegisterType((*Article_Tags)(nil), "main.Article.Tags")
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2) }

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x4d, 0x9a, 0x6c, 0xd9, 0x29, 0xad, 0x65, 0x50, 0x08, 0x9e, 0x96, 0x1e, 0x64, 0x4f,
	0x8b, 0xd6, 0x83, 0xe7, 0x4a, 0x15, 0x0b, 0x22, 0x92, 0x6e, 0xcf, 0x32, 0x76, 0x97, 0x25, 0xd0,
	0x66, 0x4b, 0x33, 0x1e, 0xfc, 0x15, 0xfe, 0x65, 0x69, 0xda, 0x5a, 0x7a, 0xcb, 0xfb, 0xde, 0x23,
	0xef, 0x31, 0xd0, 0xa7, 0x2d, 0xbb, 0xe5, 0xaa, 0x2e, 0x36, 0xdb, 0x96, 0x5b, 0x54, 0x6b, 0x72,
	0x7e, 0xf4, 0x2b, 0xa1, 0x3b, 0xd9, 0x73, 0x1c, 0x80, 0x74, 0x95, 0x11, 0x99, 0xc8, 0xb5, 0x95,
	0xae, 0xc2, 0x2b, 0xd0, 0xec, 0x78, 0x55, 0x1b, 0x99, 0x89, 0x3c, 0xb5, 0x7b, 0x81, 0x06, 0xba,
	0xcb, 0xd6, 0x73, 0xed, 0xd9, 0x74, 0x22, 0x3f, 0x4a, 0xbc, 0x83, 0x24, 0x30, 0xf1, 0x77, 0x30,
	0x2a, 0x13, 0xf9, 0x60, 0x6c, 0x8a, 0x5d, 0x45, 0x71, 0xf8, 0xbe, 0x98, 0x47, 0xaf, 0xfc, 0xd9,
	0xd4, 0xf6, 0x90, 0xc3, 0x5b, 0x50, 0x4c, 0x4d, 0x30, 0x3a, 0xeb, 0xe4, 0xbd, 0x31, 0x9e, 0xe7,
	0x4b, 0x6a, 0x82, 0x8d, 0xfe, 0xcd, 0x3d, 0xa8, 0x9d, 0xc2, 0x6b, 0x48, 0x98, 0x9a, 0xcf, 0xff,
	0x95, 0x9a, 0xa9, 0x99, 0x55, 0x88, 0xa0, 0x3c, 0xad, 0x8f, 0x3b, 0xe3, 0x7b, 0xf4, 0x08, 0x70,
	0x2a, 0xc4, 0x14, 0xf4, 0xd4, 0x4e, 0x5e, 0xca, 0xe1, 0x05, 0xf6, 0x21, 0xfd, 0x58, 0x3c, 0xbd,
	0xcd, 0xe6, 0xaf, 0xcf, 0xd3, 0xa1, 0xc0, 0x4b, 0xe8, 0x2d, 0xde, 0x4f, 0x40, 0x7e, 0x25, 0xf1,
	0x3c, 0x0f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xb2, 0xf2, 0xbf, 0x2f, 0x01, 0x00, 0x00,
}
